### PR TITLE
Add ja-JP locale

### PR DESCRIPTION
**Pull request by Cai0407**
Please add ja-JP locale.

### CODE REVIEW

**Comment by xabolcs** [comment]
Hi there!

Thanks for contributing!
Let's postpone reviewing (and landing) this PR for a few commits. There are pending string changes in the PR list.

**Comment by Cai0407** [comment]
@xabolcs I see. I will wait for the completion of string changes.

**Comment by whimboo** [comment]
I think we can continue here given that all? necessary changes have been landed meanwhile? @xabolcs can you please check?

**Comment by xabolcs** [comment]
It would be nice to land #93 and #137 before reviewing this.

**Comment by UtiluMark** [comment]
#188 will also add a few strings to the translation files.

**Comment by Cai0407** [comment]
Version 3.8 seems to be released soon.
Can I resume update of ja-JP locale now?

**Comment by UtiluMark** [comment]
Note: pending issue #188 will add a few new strings to the translation files.

**Comment by xabolcs** [comment]
@whimboo, it would be nice to clarify what to ship with 3.9 release and let @Cai0407 resume update of ja-JP locale.

**Comment by whimboo** [comment]
@xabolcs, I wouldn't add too much for a new release. It would be better to release more often instead. So I only moved all not-fixed-yet issues from 3.8 to 3.9. Also I think we shouldn't wait to long for localizers to update their locale. They should be able to do it at any time, but may have to do it again in case something else gets changed soon after.

I'm happy to get this merged after we proofed the correctness of the strings.

**Comment by Cai0407** [comment]
I have created revised PR #226.

**Comment by whimboo** [comment]
There is usually no need to create a new PR. In case of conflicts those need to be resolved locally and force pushed to your remote branch. For this time lets continue on PR #226.

**Pull request closed without merging**
