### PR TITLE
Add Czech (cs) locale

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by xabolcs** [comment]
Please be patient, looks like this will only merged when webextension port (#235) is ready.

Thanks for contributing!

**Comment by MikkCZ** [comment]
The l10n format will be probably different there, right? I have also created a PR for https://github.com/kyoshino/nightlyttr/pull/1, with the translations in messages.json format.

**Comment by xabolcs** [comment]
I saw that! Thanks!

Unsure all about that! Let be webextension first!

**Comment by kyoshino** [comment]
So #245 is now merged, but I had to remove your cs locale file added in https://github.com/kyoshino/nightlyttr/pull/1 as per @whimboo's request because it's a new locale. Would you mind adding your locale using this PR? You just need to add `extension/_locales/cs/messages.json` again and replace `XUL` with `Gecko` in that file. Thanks a lot!

**Comment by MikkCZ** [comment]
@kyoshino sorry it took me the whole week. I have updated the PR.

**Comment by whimboo** [comment]
Thanks a lot for the update! I will merge your PR now.

**Pull request merged**
