### PR TITLE
Extract Platform repository informations from "platform.ini" (#129)

### PR DESCRIPTION
**Pull request by xabolcs**
Fix for #129.

### CODE REVIEW

**Comment by whimboo** [comment]
I'm happy to continue on that PR given that I will have more time this quarter. As it looks like this PR needs some conflicts being solved first. @xabolcs if you could do that and rebase to latest master, lets get this request merged into master soon. I will ensure to do fast follow-up reviews.

**Comment by xabolcs** [comment]
There are open questions here to both of us, but a merge from master is a must. :)

**Comment by whimboo** [comment]
Totally. Once done please let me know to which questions you need an answer from me. Thanks!

**Comment by xabolcs** [comment]
Merge done, but nothing else. I'll let you know if I'm done with resuming this PR.

**Comment by tonymec** [comment]
@xabolcs : I took the liberty to package your branch-issue-129-platform-changeset branch head into an "experimental XPI", like what you did in April 2013. Shall I upload it to AMO as the latest "development" version of this add-on (and thus close my newest issue #202)?

I know that the future of comm-central is uncertain; but this feature will remain useful as long as there exist one or more versions of Thunderbird and/or SeaMonkey in current use (even if recently obsoleted by the next version) whose source includes an identifiable mozilla-something repository at ./mozilla or even elsewhere (with -something being one of -central, -aurora, -beta and -release, of course).

**Comment by whimboo** [comment]
Personally I wouldn't say that we should upload developer versions to AMO with code included which has not been fully reviewed and landed yet.

**Comment by tonymec** [comment]
UA:"Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0 SeaMonkey/2.45a1"
ID:20160308003002 en-US
c-c:05c087337043dd8e71cc27bdb5b9d55fd00aaa26
m-c:05c087337043dd8e71cc27bdb5b9d55fd00aaa26

Actually, c-c is from http://hg.mozilla.org/comm-central/rev/3e342c12aed2

NTT nightlytt-3.8pre-201601030947.xpi from (IIRC) branch xabolcs/branch-issue-129-platform-changeset

As can be seen above, ${Changeset} and ${PlatformChangeset} are now the same (equal to the mozilla-central CSID) and the comm-central CSID is gone.

I get the latter from the .txt file which accompanies the .tar.bz2 at ftp.mozilla.org (e.g. in this case: seamonkey-2.45a1.en-US.linux-x86_64.txt).

Last good: 2.44a1 from https://l10n.mozilla-community.org/~akalla/unofficial/seamonkey/nightly/latest-comm-central-linux64/
20160208023510
https://hg.mozilla.org/mozilla-central/rev/1cfe34ea394c66d7fa2c6dc366b05ab00e919113
https://hg.mozilla.org/comm-central/rev/4a60c0ffe9af

First bad: 2.45a1 from http://ftp.mozilla.org/pub/seamonkey/nightly/latest-comm-central-trunk/
20160308003002
http://hg.mozilla.org/mozilla-central/rev/05c087337043dd8e71cc27bdb5b9d55fd00aaa26
http://hg.mozilla.org/comm-central/rev/3e342c12aed2

I wonder what may have changed in about one month of non-building.

**Comment by xabolcs** [comment]
> As can be seen above, ${Changeset} and ${PlatformChangeset} are now the same (equal to the mozilla-central CSID) and the comm-central CSID is gone.

@tonymec, please file a bug about this in the Bugzilla! it's very interesting.

**Comment by tonymec** [comment]
On Sun, Aug 28, 2016 at 11:02 PM, Szabolcs Hubai
<notifications@github.com> wrote:
> As can be seen above, ${Changeset} and ${PlatformChangeset} are now the same
> (equal to the mozilla-central CSID) and the comm-central CSID is gone.
>
> @tonymec, please file a bug about this in the Bugzilla! it's very
> interesting.

I had not noticed it before, but for at least 4 days (I don't have
earlier ones), the seamonkey-2.48a1.en-US.linux-x86_64.txt includes
the comm-central URI twice (with long and short CSID). The last time I
copied them into a bug (but when was that) they were the long m-c CSID
and the short c-c CSID, and yet, at that time ${Changeset} and
${PlatformChangeset} were already equal (to each other and to the
comm-central CSID). It is the _mozilla-central_ CSID which is gone.
${Changeset} has always been the comm-central CSID, and
${PlatformChangeset}, which was added to reflect the mozilla-central
CSID, points now also to comm-central.

For instance, in my present SeaMonkey build, they both point to
http://hg.mozilla.org/comm-central/rev/60b332e98e134900539934e6f1cb41461857ddce
which exists at the corresponding date (13 hours ago, and this build
is 20160828013444).

I'll file this in SeaMonkey :: Release Engineering and CC you on the
bug. If you want to move it elsewhere, feel free to, but remember that
it is *not permitted* to Mozilla employees to even raise a little
finger to the help of SeaMonkey on company time. This is official MoCo
policy.

Best regards,
Tony.

**Comment by tonymec** [comment]
On Sun, Aug 28, 2016 at 11:52 PM, Tony Mechelynck
<antoine.mechelynck@gmail.com> wrote:
> On Sun, Aug 28, 2016 at 11:02 PM, Szabolcs Hubai
> <notifications@github.com> wrote:
>> As can be seen above, ${Changeset} and ${PlatformChangeset} are now the same
>> (equal to the mozilla-central CSID) and the comm-central CSID is gone.
>>
>> @tonymec, please file a bug about this in the Bugzilla! it's very
>> interesting.
>
> I had not noticed it before, but for at least 4 days (I don't have
> earlier ones), the seamonkey-2.48a1.en-US.linux-x86_64.txt includes
> the comm-central URI twice (with long and short CSID). The last time I
> copied them into a bug (but when was that) they were the long m-c CSID
> and the short c-c CSID, and yet, at that time ${Changeset} and
> ${PlatformChangeset} were already equal (to each other and to the
> comm-central CSID). It is the _mozilla-central_ CSID which is gone.
> ${Changeset} has always been the comm-central CSID, and
> ${PlatformChangeset}, which was added to reflect the mozilla-central
> CSID, points now also to comm-central.
>
> For instance, in my present SeaMonkey build, they both point to
> http://hg.mozilla.org/comm-central/rev/60b332e98e134900539934e6f1cb41461857ddce
> which exists at the corresponding date (13 hours ago, and this build
> is 20160828013444).
>
> I'll file this in SeaMonkey :: Release Engineering and CC you on the
> bug. If you want to move it elsewhere, feel free to, but remember that
> it is *not permitted* to Mozilla employees to even raise a little
> finger to the help of SeaMonkey on company time. This is official MoCo
> policy.
>
> Best regards,
> Tony.

I found bug 456360 in Toolkit :: Build Config, which seemed to already
cover the problem, so I added a comment there describing the latest
developments, and added you two, and the SeaMonkey RelEng prople, to
the CC.

Best regards,
Tony.

**Comment by xabolcs** [comment]
> I found bug 456360 in Toolkit :: Build Config, which seemed to already cover the problem ...

Nice findings, thanks!

**Comment by xabolcs** [comment]
Using the WebExtension API outdated this PR.

WebExtension experiments should help here, IMHO.

**Pull request closed without merging**
