### PR TITLE
update ja and ja-JP-mac translation

### PR DESCRIPTION
**Pull request by Cai0407**
Japanese L10N guideline of Mozilla products has been updated (target milestone: Firefox/Thunderbird 52).
Here are updated ja and ja-JP-mac translations of NTT based on the new guideline.
Already reviewed by @marsf via e-mail.

### CODE REVIEW

**Comment by whimboo** [comment]
@marsf mind approving it officially? Thanks.

**Comment by whimboo** [comment]
Thanks! Just a question still... should we get this out soonish before the 52 release, or is it enough when we do a release when we have enough changes for the next version of NTT?

**Comment by marsf** [comment]
I think releasing it with the next version of NTT is enough.
The change has no meaning changes nor corrections.

**Comment by Cai0407** [comment]
I agree with @marsf.

**Pull request merged**
