### PR TITLE
Reduced the whitespace above the main heading on the about screen

### PR DESCRIPTION
**Pull request by UtiluMark**
Part of #188

### CODE REVIEW

**Comment by UtiluMark** [comment]
@whimboo Please review and merge.

**Comment by xabolcs** [comment]
@UtiluMark, I don't see the difference with latest Nightly. Could you post some before-after screenshots?

**Comment by UtiluMark** [comment]
@xabolcs
about:nightly before reducing the margin above "Nightly Tester Tools":
ntt pr 194 about nightly before
about:nightly after reducing the margin above "Nightly Tester Tools":
ntt pr 194 about nightly after

**Comment by whimboo** [comment]
Makes sense to me, so r=me. I will land it in a moment.

**Comment by whimboo** [comment]
Merged the PR as https://github.com/mozilla/nightlytt/commit/9e83e43239e60e2d8cf8b9aacc10fd19862b2bbc. Thank you for the patch!

**Pull request closed without merging**
