### PR TITLE
Port back code-changes from Utilu Nightly Tester Tools 3.7.1.1

### PR DESCRIPTION
**Pull request by UtiluMark**
* Extension: The extension is now signed. Mozilla began requiring all extensions to be signed in order for them to be installable in Release and Beta versions of Firefox. Signing is done through addons.mozilla.org (AMO) and has become mandatory for all extensions.
* Extension: Removed all partially incomplete translations
* Extension: Removed excessive white space before line endings
* Extension: Removed unused variables module
* Extension: Removed references to End-of-life (EOL) extensions
* Extension: Fixed indentation by always using spaces and never using tabs
* Extension: Removed copy to Pastebin functionality which had become non-working due to API changes
* Extension: Replaced non-working copy to Pastebin functionality by copy text to Clipboard functionality
* Extension: Added spaces between the extensions when copying the list of extensions to the Clipboard
* Extension: Removed non-working image hosts
* Extension: Increased the size of the Customize Titlebar window
* Extension: Improved default Customized Titlebar title
* Extension: Optimized the order of the Customize Titlebar Variables
* Extension: Added Customize Titlebar Variable Application Version Pretty
* Extension: Added Customize Titlebar Variable Application Update Channel
* Extension: Added Customize Titlebar Variable Application Update Channel Pretty (Release, ESR, beta, Aurora, Nighty, Default)
* Extension: Added Customize Titlebar Variable Application Version and Channel
* Extension: Added Customize Titlebar Variable Number of visible tabs
* Extension: Fixed missing vendor in Titlebar Customization in Thunderbird
* Extension: Marked Crash me options which do not cause a crash as such
* Extension: Removed the unused CSS files
* Extension: Cleaned and optimized the remaining CSS files
* Extension: Updated and synced feature lists
* Extension: Updated maxVersions for applications
* Extension: Minor changes and improvements

### CODE REVIEW

**Comment by whimboo** [comment]
I like a lot of those changes but it's really nothing we can land. If you want to get your changes into the core code base of NTT we would appreciate that. But it should happen in smaller steps, and only those bits which would not conflict (like the change of the addon id).

**Comment by UtiluMark** [comment]
What would be the best approach to get the changes you like into the core code base of NTT?

**Comment by whimboo** [comment]
Hey, thanks for getting back to us and the interest to bring back your code changes into the main developer tree. So having a quick look at the list of changes I think that the following might be a good way to get it done:

* Removal of unused files
* Code clean-up of all the files
* Customize title bar enhancements
* Other PRs for remaining things

Would that work for you?

**Comment by UtiluMark** [comment]
Thank you. I've created a new fork of NTT, and started to re-apply the changes one by one. I've just submitted a separate pull request #187 for the first change (Removal of unused files). Is this the way to go? Then I'll create separate pull request for the remaining changes as well.

**Comment by whimboo** [comment]
Yes, that looks totally fine. Thanks!

**Comment by whimboo** [comment]
If you want to be assigned to this issue I would suggest that you join our team:
https://github.com/orgs/mozilla/teams/firefox-automation-contributor

**Comment by UtiluMark** [comment]
I get a 404 Page not found on the URL you've posted. Could you add me to the team? Thanks.

**Comment by whimboo** [comment]
I'm going to close this PR given that we don't want to take the full code changes at once. Instead lets file a new issue for tracking purposes.

**Pull request closed without merging**
