### PR TITLE
Removed reference to End-of-life (EOL) Screengrab extension

### PR DESCRIPTION
**Pull request by UtiluMark**
Part of #188

### CODE REVIEW

**Comment by UtiluMark** [comment]
@whimboo Please review and merge.

**Comment by whimboo** [comment]
I agree here, but also wonder if there is another add-on we could promote or even integrate a screenshot feature in NTT itself. In combination with a working upload service it would be great to quickly share issues in newest nightly builds.

**Comment by whimboo** [comment]
Merged the PR as https://github.com/mozilla/nightlytt/commit/6326ede95b40225d43e508cfd475b4876076c77a. Thank you for the patch!

**Comment by UtiluMark** [comment]
@whimboo Perhaps the easiest way to do that would be to switch to the updated version of Screengrab (last updated less than a month ago):
https://addons.mozilla.org/en-US/firefox/addon/screengrab-fix-version/
Shall I create a new PR in which I add it?

**Comment by whimboo** [comment]
I think it's worth a look. Lets file a new issue for now so we can get it discussed. Also it looks like it has an image upload feature. So we may be able to strip all that off from our extension if we could collaborate.

**Comment by UtiluMark** [comment]
@whimboo I've added a link to the Screengrab (fix version) add-on in PR #198.

**Pull request closed without merging**
