### PR TITLE
Sort variables alphabetically in customize.js

### PR DESCRIPTION
**Pull request by ritwikmishra**
Variable tabs from `Line 86` to `Line 105` have been sorted successfully

### CODE REVIEW

**Comment by xabolcs** [comment]
Not tested, but it looks good to me!

@whimboo, could you have another pair of eye before landing?

**Comment by xabolcs** [comment]
> Not tested, but it looks good to me!

I'll test this locally later today, and land it.

**Comment by whimboo** [comment]
Yes, looks fine to me. Thank you @ritwikmishra.

@xabolcs when you land it please make sure to first update the commit message. Thanks!

**Comment by xabolcs** [comment]
Landed as commit 6f1c7e88ab9a4c35c8d44a3cd8cab8b170656112.

**Pull request closed without merging**
